### ISSUE TITLE
Support for Codelists version release 57

### ISSUE THREAD

**Issue by preetsin** [zach-m/jonix#19]
https://www.editeur.org/93/Release-3.0-Downloads/#Codes

**Comment by zach-m** [comment]
it's right here:
<https://github.com/zach-m/jonix/blob/master/jonix-common/src/main/java/com/tectonica/jonix/common/codelist/MeasureUnits.java>

What kind of "support" are you referring to?

**Comment by preetsin** [comment]
Thank you for your prompt response.

I am referring to new code lists issue 50 changes.
https://www.editeur.org/files/ONIX%20for%20books%20-%20code%20lists/ONIX_BookProduct_Codelists_Issue_50_Changes.pdf

**Comment by preetsin** [comment]
Hi @zach-m,

The latest Codelists version (not the codelist) 57 was published in Apr-2022. The JONIX supports the Codelists version release 49.

Is there any plan to update the JONIX to support the new Codelists version 57?

The following PDF document shows the changes made to Codelists in version 57.
https://www.editeur.org/files/ONIX%20for%20books%20-%20code%20lists/ONIX_BookProduct_Codelists_Issue_57_Changes.pdf

**Comment by zach-m** [comment]
Support added in version 2022-08
