### ISSUE TITLE
Onix3 product long description is parsed wrongly when we pass html format inside CDATA tag.It is parsed something like this "<<Text textformat="02" xmlns="http://ns.editeur.org/onix/3.0/reference"/>> "

### ISSUE THREAD

**Issue by sravanikavuri** [zach-m/jonix#26]
we are using 8.x version of Jonix.

sample text we pass in xml
<CollateralDetail>
			<TextContent>
				<TextType>03</TextType>
				<ContentAudience>00</ContentAudience>
				<Text textformat="02"><![CDATA[<b>Hello</b>]]></Text>
			</TextContent>
</CollateralDetail>

**Comment by sravanikavuri** [comment]
Any information on this?the content inside tag is empty if we pass content inside cdata.

**Comment by rpinto-pe** [comment]
Hi. Any help on how to overcome this issue and get text inside CDATA?

**Comment by zach-m** [comment]
See #32
