### ISSUE TITLE
Typo for BISAC subject code

### ISSUE THREAD

**Issue by Green-Beret** [zach-m/jonix#34]
lots of classes, methods with this subject is called BASIC.
Such as com.tectonica.jonix.onix2.BASICMainSubject, com.tectonica.jonix.onix2.Product.basicVersion() etc.

**Comment by zach-m** [comment]
all the code, and particularly class names, is generated from the Onix specifications directly. As the tag name in Onix is `<BASICMainSubject>`, the class name follows.

EDItEUR have commented in the past about this specific mix-up:
```
Note that the data element reference name was assigned during a period when the BISAC name had been changed to “BASIC”.
The name has now officially reverted to “BISAC”, but the ONIX data element name cannot be changed for reasons of upwards compatibility.
```
