### ISSUE TITLE
Custom date deserializer

### ISSUE THREAD

**Issue by phillippc** [zach-m/jonix#7]
First of all I would like to extend my gratitude for the work on this library!
Is there a way to define a custom date deserializer for this case:
java.lang.RuntimeException: java.text.ParseException: Unparseable date: "201910"
	at com.tectonica.jonix.util.JonixUtil.parseYYYYMMDD(JonixUtil.java:70)

Some of the onix feeds we receive, come with crappy date formats. Ive been googling around but could not find anything.
Any help is much appreciated!
Regards,
Phillipp

**Comment by zach-m** [comment]
@phillippc I see that parseYYYYMMDD() gets called only by [PublishingDetails](https://github.com/zach-m/jonix/blob/master/jonix/src/main/java/com/tectonica/jonix/unify/base/BasePublishingDetails.java), where indeed there's a "TODO" note for more careful date manipulation..

What are you doing exactly that takes you to this code path? maybe paste the entire stack-trace here.

Also, which version of Jonix are you using? and do you compile from Code or just using it as a dependency?

**Comment by zach-m** [comment]
Anyway, apparently "201910" is not a "crappy date format", and is in fact valid.
I added a fix to the code, but unless you're building from source you won't see it.
I'll do a minor release soon.
